/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6/samples
 */

import org.apache.tools.ant.filters.ReplaceTokens

plugins {
	base
}

tasks.register<Copy>("generateDescriptions") {
	from("descriptions")
	into("$buildDir/descriptions")
	filter(ReplaceTokens::class, "tokens" to mapOf("THEME_PARK_NAME" to "Grelephant's Wonder World"))
}